ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS deck_7day_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS deck_1day_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS deck_expired_email_sent BOOLEAN NOT NULL DEFAULT FALSE;
